name: rl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - torch
  - numpy
  - matplotlib
  - gymnasium
  - gymnasium[box2d]
  - tqdm
  - pip
  - pyyaml
  - moviepy
  - pip:
    - pettingzoo[mpe]
    - swig
    - box2d-py