name: rl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
    - torch
    - tensorboard
    - numpy
    - matplotlib
    - gymnasium
    - gymnasium[box2d]
    - gymnasium[atari]
    - gymnasium[accept-rom-license]
    - gymnasium[mujoco]
    - gymnasium[other]
    - tqdm
    - pip
    - pyyaml
    - moviepy
    - pettingzoo[mpe]
    - swig
    - box2d-py
    - tyro
    - stable_baselines3
    - wandb